#
# Specific set up for Kitchen CYD
#
# ============================================================ 
# NOTE:
# In order for this to work you need to add the following settings in your secrets.yaml file:
# - kit_api_key
#
# Create a folder named fonts in your ESPHome folder, and copy the file fonts/Arimo-Regular.ttf there.
#
# ============================================================ 
# Example file setup
# Change the naming below, they will be the names used in Home Assistant
#
substitutions:
  device_name: esphome-web-7a995c
  friendly_name: Kitchen CYD
#  base_page: page1

# ============================================================ 
packages:
  cyd: !include common/CYD.yaml
  device_base: !include common/device_base.yaml

# ============================================================ 

# Enable Home Assistant API
api:
  encryption:
    key: !secret kit_api_key

# Update the UI state every 10 seconds
interval:
  - interval: 10s
    then:
      - script.execute: update_ui_values
    # Every 60 seconds check to see if we had a recent touch and
    # turn off the backlight if we haven't.  This does mean that it 
    # can be up to 2 minutes until the backlight turns off
  - interval: 60s
    then:
      - if:
          condition:
            - lambda: |-
                return !id(recent_touch);
          then: 
            - light.turn_off:
                id: backlight
            - display.page.show: page1
            # How to make this work?:
            # - display.page.show: ${base_page}
          else:
            - lambda: |-
                id(recent_touch) = false;
