#
# Basic yaml code to get the ESP32-2432S028R display to work in ESPHome.
#
# This yaml displays four rectangles acting as binary touch sensors inside of Home Assistant.
#
# Originally written by Jonny Bergdahl
# - [GitHub](https://github.com/jonnybergdahl)
# - [Twitter](https://twitter.com/jonnybergdahl)
# - [YouTube](https://www.youtube.com/jonnybergdahl)
#
# ============================================================ 
# NOTE:
# In order for this to work you need to add the following settings in your secrets.yaml file:
# - api_key
# - ota_password
# - wifi_ssid
# - wifi_password
# - ap_password
#
# Create a folder named fonts in your ESPHome folder, and copy the file fonts/Arimo-Regular.ttf there.
#
# ============================================================ 
# Example file setup
# Change the naming below, they will be the names used in Home Assistant
#
substitutions:
  device_name: esphome-web-abbb34
  friendly_name: Living Room CYD
  base_page: page2

# ============================================================ 
packages:
  cyd: !include common/CYD.yaml
  device_base: !include common/device_base.yaml

# ============================================================ 

# Enable Home Assistant API
api:
  encryption:
    key: !secret lroom_api_key

